const mongoose = require('mongoose');

const taskSchema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId, // Automatically generated by Mongoose
  title: {
    type: String,
    required: true, // Assuming every task must have a title
  },
  description: {
    type: String,
    required: true, // Assuming every task must have a description
  },
  dueDate: {
    type: Date,
    required: true, // Assuming every task must have a due date
  },
});

const classroomSchema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId, // Automatically generated by Mongoose
  name: {
    type: String,
    required: true, // Assuming every classroom must have a name
  },
  teacher: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Teacher', // Reference to the Teacher model
    required: true, // Assuming every classroom must have a teacher
  },
  students: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Student', // Reference to the Student model
  }],
  tasks: [taskSchema] // Embedded array of task documents
});

const Classroom = mongoose.model('Classroom', classroomSchema);

module.exports = Classroom;
