const mongoose = require('mongoose');

const teacherSchema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId, // Automatically generated by Mongoose
  name: {
    type: String,
    required: true, // Assuming every teacher must have a name
  },
  email: {
    type: String,
    required: true, // Assuming every teacher must have an email
    unique: true, // To enforce uniqueness of emails
  },
  classrooms: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Classroom' // Reference to the Classroom model
  }]
});

const Teacher = mongoose.model('Teacher', teacherSchema);

module.exports = Teacher;
